
language: node_js
node_js:
  - "11.1.0"
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install -g nauchikus/typescript-definitive-guide#builder

script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dest/
  keep-history: true
  on:
    branch: master